<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Test\Parent;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ParentTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'parents';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'id',
            'customer_id',
            'date',
            'reference',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'id' => (object) [
                'name' => 'id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'customer_id' => (object) [
                'name' => 'customer_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'date' => (object) [
                'name' => 'date',
                'type' => 'date',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'reference' => (object) [
                'name' => 'reference',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'id' => null,
            'customer_id' => '0',
            'date' => null,
            'reference' => null,
        ];
    }
}
